### ISSUE TITLE
Installing over oxygen breaks DLTK

### ISSUE THREAD

**Issue by olberger** [pulse00/Symfony-2-Eclipse-Plugin#253]
Installing over oxygen leads to:

An internal error occurred during: "Initialize DLTK".
java.lang.NoClassDefFoundError: org/eclipse/php/internal/core/compiler/ast/visitor/PHPASTVisitor

See some related report in https://stackoverflow.com/questions/44848437/eclipse-could-not-open-editor-after-eclipse-pdt-upgrade-to-version-5-0-1-20170#comment76825341_44848437

Hope this helps,

**Comment by zulus** [comment]
Working correctly with recent release. User have to update both PDT and it's plugins.

**Comment by olberger** [comment]
Oops, didn't see your response @zulus.

But... how's one supposed to manage the update ? Just tested with the link in the README... and I still go 1.3.1.

**Comment by nelson777** [comment]
Same problem here. Updated all plugins. The current file tab in the editor gets corrupted and doesn't show file name anyome. Only the X for closing. Is there any debug data I can send ?

**Comment by zulus** [comment]
Eclipse 4.7 build have 2017 in build date. Tou haven't latest version. Please unistall sf plugins completely and try install again

**Comment by zulus** [comment]
sorry, there was a bug in build script. Please try update again.

**Comment by olberger** [comment]
I confirm that the update is now operational. Just updated from Neon.3 to Oxygen, and no more problems with the DLTK indexing

**Comment by nelson777** [comment]
I deleted the whole .metadata of the workspace and restarted. Reinstalled PDT Extensions and it worked.

**Comment by FredDut** [comment]
Is it possible the same bug occurs with SimRel2018-09 and PDT 6.1?
After migrating from oxygen to 2018-09, the buid fails (with SF plugin from market place):
Errors occurred during the build.
Errors running builder 'Script Builder' on project 'wz33'.
org/eclipse/php/internal/core/compiler/ast/visitor/PHPASTVisitor ?
